package com.sohu_inc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-17T20:56:00.305+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://focuscrm.sohu-inc.com/", name = "HouseSysServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface HouseSysServiceSoap {

    /**
     * 获取CRM中的销售
     */
    @WebMethod(operationName = "GetSales", action = "http://focuscrm.sohu-inc.com/GetSales")
    @RequestWrapper(localName = "GetSales", targetNamespace = "http://focuscrm.sohu-inc.com/", className = "com.sohu_inc.focuscrm.GetSales")
    @ResponseWrapper(localName = "GetSalesResponse", targetNamespace = "http://focuscrm.sohu-inc.com/", className = "com.sohu_inc.focuscrm.GetSalesResponse")
    @WebResult(name = "GetSalesResult", targetNamespace = "http://focuscrm.sohu-inc.com/")
    public com.sohu_inc.ArrayOfSales getSales(
            @WebParam(name = "sSalesName", targetNamespace = "http://focuscrm.sohu-inc.com/")
                    String sSalesName,
            @WebParam(name = "sKey", targetNamespace = "http://focuscrm.sohu-inc.com/")
                    String sKey
    );

    /**
     * 同步成交确认单及明细
     */
    @WebMethod(operationName = "DealConfirmSync", action = "http://focuscrm.sohu-inc.com/DealConfirmSync")
    @RequestWrapper(localName = "DealConfirmSync", targetNamespace = "http://focuscrm.sohu-inc.com/", className = "com.sohu_inc.focuscrm.DealConfirmSync")
    @ResponseWrapper(localName = "DealConfirmSyncResponse", targetNamespace = "http://focuscrm.sohu-inc.com/", className = "com.sohu_inc.focuscrm.DealConfirmSyncResponse")
    @WebResult(name = "DealConfirmSyncResult", targetNamespace = "http://focuscrm.sohu-inc.com/")
    public com.sohu_inc.ResultInfo dealConfirmSync(
            @WebParam(name = "sDataInfo", targetNamespace = "http://focuscrm.sohu-inc.com/")
                    String sDataInfo,
            @WebParam(name = "sKey", targetNamespace = "http://focuscrm.sohu-inc.com/")
                    String sKey
    );

    /**
     * 调整成交确认单电商金额及电商代收代付金额
     */
    @WebMethod(operationName = "UpdateDsPayPrice", action = "http://focuscrm.sohu-inc.com/UpdateDsPayPrice")
    @RequestWrapper(localName = "UpdateDsPayPrice", targetNamespace = "http://focuscrm.sohu-inc.com/", className = "com.sohu_inc.focuscrm.UpdateDsPayPrice")
    @ResponseWrapper(localName = "UpdateDsPayPriceResponse", targetNamespace = "http://focuscrm.sohu-inc.com/", className = "com.sohu_inc.focuscrm.UpdateDsPayPriceResponse")
    @WebResult(name = "UpdateDsPayPriceResult", targetNamespace = "http://focuscrm.sohu-inc.com/")
    public com.sohu_inc.ResultInfo updateDsPayPrice(
            @WebParam(name = "sDataInfo", targetNamespace = "http://focuscrm.sohu-inc.com/")
                    String sDataInfo,
            @WebParam(name = "sKey", targetNamespace = "http://focuscrm.sohu-inc.com/")
                    String sKey
    );

    /**
     * 获取CRM中的经纪公司
     */
    @WebMethod(operationName = "GetCompany", action = "http://focuscrm.sohu-inc.com/GetCompany")
    @RequestWrapper(localName = "GetCompany", targetNamespace = "http://focuscrm.sohu-inc.com/", className = "com.sohu_inc.focuscrm.GetCompany")
    @ResponseWrapper(localName = "GetCompanyResponse", targetNamespace = "http://focuscrm.sohu-inc.com/", className = "com.sohu_inc.focuscrm.GetCompanyResponse")
    @WebResult(name = "GetCompanyResult", targetNamespace = "http://focuscrm.sohu-inc.com/")
    public com.sohu_inc.ArrayOfCompany getCompany(
            @WebParam(name = "sCompanyName", targetNamespace = "http://focuscrm.sohu-inc.com/")
                    String sCompanyName,
            @WebParam(name = "sKey", targetNamespace = "http://focuscrm.sohu-inc.com/")
                    String sKey
    );
}
