
package com.sohu_inc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-17T20:56:00.257+08:00
 * Generated source version: 3.1.9
 * 
 */
public final class HouseSysServiceSoap_HouseSysServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://focuscrm.sohu-inc.com/", "HouseSysService");

    private HouseSysServiceSoap_HouseSysServiceSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = HouseSysService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HouseSysService ss = new HouseSysService(wsdlURL, SERVICE_NAME);
        HouseSysServiceSoap port = ss.getHouseSysServiceSoap();  
        
        {
        System.out.println("Invoking getSales...");
        String _getSales_sSalesName = "";
        String _getSales_sKey = "";
        com.sohu_inc.ArrayOfSales _getSales__return = port.getSales(_getSales_sSalesName, _getSales_sKey);
        System.out.println("getSales.result=" + _getSales__return);


        }
        {
        System.out.println("Invoking dealConfirmSync...");
        String _dealConfirmSync_sDataInfo = "";
        String _dealConfirmSync_sKey = "";
        com.sohu_inc.ResultInfo _dealConfirmSync__return = port.dealConfirmSync(_dealConfirmSync_sDataInfo, _dealConfirmSync_sKey);
        System.out.println("dealConfirmSync.result=" + _dealConfirmSync__return);


        }
        {
        System.out.println("Invoking updateDsPayPrice...");
        String _updateDsPayPrice_sDataInfo = "";
        String _updateDsPayPrice_sKey = "";
        com.sohu_inc.ResultInfo _updateDsPayPrice__return = port.updateDsPayPrice(_updateDsPayPrice_sDataInfo, _updateDsPayPrice_sKey);
        System.out.println("updateDsPayPrice.result=" + _updateDsPayPrice__return);


        }
        {
        System.out.println("Invoking getCompany...");
        String _getCompany_sCompanyName = "";
        String _getCompany_sKey = "";
        com.sohu_inc.ArrayOfCompany _getCompany__return = port.getCompany(_getCompany_sCompanyName, _getCompany_sKey);
        System.out.println("getCompany.result=" + _getCompany__return);


        }

        System.exit(0);
    }

}
